name: gmaps_multidestination
description: Get travel times to multiple destinations in batch
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 google_maps_webservice: ^0.0.17
 batching_future: ^1.0.0
 meta: ^1.2.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  args:
